// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKS3T2ZHarN1rQCofc7rQAwL9AaW2bbw',
    appId: '1:28651080381:web:92354cde72b334e03a05d4',
    messagingSenderId: '28651080381',
    projectId: 'chat-app-4b38b',
    authDomain: 'chat-app-4b38b.firebaseapp.com',
    storageBucket: 'chat-app-4b38b.appspot.com',
    measurementId: 'G-2DQ1TSW6QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlqmFseULEAyHZ68e6Gi-eebiRcXsLz0I',
    appId: '1:28651080381:android:92f344e291cbba673a05d4',
    messagingSenderId: '28651080381',
    projectId: 'chat-app-4b38b',
    storageBucket: 'chat-app-4b38b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlla_Y_o_tVKbtf-zF8w3fPaAF9KYMUjw',
    appId: '1:28651080381:ios:1ed82d471515fdae3a05d4',
    messagingSenderId: '28651080381',
    projectId: 'chat-app-4b38b',
    storageBucket: 'chat-app-4b38b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlla_Y_o_tVKbtf-zF8w3fPaAF9KYMUjw',
    appId: '1:28651080381:ios:d22bb212d5d3c9dd3a05d4',
    messagingSenderId: '28651080381',
    projectId: 'chat-app-4b38b',
    storageBucket: 'chat-app-4b38b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
